#
# tuned configuration
#

[main]
summary=Broadly applicable tuning that provides excellent performance across a variety of common server workloads
include=throughput-performance

[cpu]
governor=ondemand
energy_performance_preference=performance

[script]
script=${i:PROFILE_DIR}/script.sh

