# Default power profile
# (taken from below [profiles]/[battery] depending on power source)
[main]
default=balanced
battery_detection=true
sysfs_acpi_monitor=true

# Power profiles on AC
[profiles]
power-saver=custom-powersave
balanced=custom-balanced
performance=custom-performance

# Power profiles for battery
[battery]
power-saver=custom-powersave-battery
balanced=custom-balanced-battery
performance=custom-performance-battery
