# SWAP: 3/4 of installed physical RAM with lz4 compression for speed
[zram0]
zram-size = (ram - ram / 4)
compression-algorithm = lz4

# Temporary log storage: tiny, in-RAM ext2 partition
[zram1]
zram-size = 195
fs-type = ext2
mount-point = /var/log
